# Generated by Django 5.1.6 on 2025-03-17 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('shop', '0027_alter_flavoursize_available_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.flavour'),
        ),
    ]
